Repository dalsu0222/NFE1-1-3-DevPorest_Backend, pull requests merged in 2024-10, with the labels that each got.

#5 [FEAT] Swagger 기본 환경 세팅
  index.js
  package-lock.json
  package.json
  swagger/index.js
Labels: ✨ Feature, ⚙ Setting

#6 ✨ 포트폴리오 스키마 작성
  models/Portfolio.js
Labels: ✨ Feature

#9 Feat/#8 portfolio crud api
  controllers/portfolioController.js
  index.js
  models/Portfolio.js
  routes/index.js
  routes/portfolioRoutes.js
  swagger/index.js
Labels: ✨ Feature, 🔨 Refactor

#11 [FEAT] 포트폴리오 수정, 삭제, 상세조회 api 구현
  controllers/portfolioController.js
  routes/portfolioRoutes.js
Labels: ✨ Feature

#12 [FEAT] Github OAuth Login 구현
  controllers/authController.js
  index.js
  middleware/auth.js
  routes/authRoute.js
Labels: ✨ Feature

#14 [FEAT] User API CRUD 구현
  controllers/authController.js
  controllers/userController.js
  middleware/auth.js
  models/User.js
  routes/index.js
  routes/userRoutes.js
Labels: ✨ Feature

#16 [FEAT] TechStack Schema 생성 및 API 구현
  controllers/techStackController.js
  models/TechStack.js
  routes/index.js
  routes/techStackRoute.js
Labels: ✨ Feature

#18 [FEAT] 포트폴리오 검색 api 구현
  controllers/portfolioController.js
  models/Portfolio.js
  routes/portfolioRoutes.js
Labels: ✨ Feature, 🔨 Refactor

#22 [FEAT] portfolio api 인증 추가
  controllers/authController.js
  controllers/portfolioController.js
  models/Portfolio.js
  models/User.js
  routes/authRoute.js
  routes/portfolioRoutes.js
  swagger/index.js
Labels: ✨ Feature, 🔨 Refactor

#23 [FEAT] 좋아요 관련 API 및 기능 구현
  controllers/portfolioController.js
  controllers/userController.js
  models/Like.js
  routes/portfolioRoutes.js
  routes/userRoutes.js
Labels: ✨ Feature

#27 [FEAT] JobGroup API 구현
  controllers/jobGroupController.js
  models/JobGroup.js
  routes/index.js
  routes/jobGroupRoute.js
  routes/portfolioRoutes.js
Labels: ✨ Feature

#29 [FEAT] 단일/다중 이미지 업로드 api 구현
  controllers/authController.js
  controllers/portfolioController.js
  middleware/upload.js
  package-lock.json
  package.json
  routes/authRoute.js
  routes/portfolioRoutes.js
Labels: ✨ Feature, 🔨 Refactor

#30 [FEAT] 인기 유저 조회 API 구현
  controllers/userController.js
  routes/index.js
  routes/userRoutes.js
Labels: ✨ Feature, 🔨 Refactor

#32 [REFACTOR] 유저 조회 api 좋아요 로직 수정 & 코드 개선
  controllers/userController.js
  routes/userRoutes.js
Labels: 🔨 Refactor

#34 [FEAT] Comment CRUD api 구현
  controllers/commentController.js
  models/Comment.js
  models/Portfolio.js
  routes/commentRoutes.js
  routes/index.js
Labels: ✨ Feature, 🔨 Refactor

#39 [FEAT] 기술스택 통계 API 구현
  controllers/techStackController.js
  models/TechStack.js
  routes/techStackRoute.js
Labels: ✨ Feature, 🔨 Refactor

#36 [FEAT] portfolio 조회/검색 api에 pagination 추가
  controllers/commentController.js
  controllers/portfolioController.js
  routes/portfolioRoutes.js
Labels: ✨ Feature, 🔨 Refactor

#40 [FEAT] 유저 포트폴리오 조회 api 구현
  controllers/portfolioController.js
  routes/portfolioRoutes.js
Labels: ✨ Feature

#42 [FEAT] 유저가 좋아요 누른 포트폴리오 조회 api 구현
  controllers/portfolioController.js
  routes/portfolioRoutes.js
Labels: ✨ Feature, 🔨 Refactor

#43 [FEAT] 포트폴리오 조회수 기능
  controllers/authController.js
  controllers/portfolioController.js
  index.js
  package-lock.json
  package.json
  utils/viewCounter.js
Labels: ✨ Feature, 🔨 Refactor

#45 ♻️ 중복 조회수 방지 로직 변경
  controllers/portfolioController.js
  utils/viewCounter.js
Labels: 🔨 Refactor

#46 [REFACTOR] 유저 조회 API 리팩토링
  controllers/userController.js
  routes/userRoutes.js
Labels: 🔨 Refactor

#50 [REFACTOR] 기술스택 API 리팩토링
  controllers/techStackController.js
  routes/techStackRoute.js
Labels: 🔨 Refactor

#49 [REFACTOR] 포트폴리오 조회 관련 api 리팩토링 작업
  controllers/portfolioController.js
  pipeline/portfolioPipeline.js
  routes/portfolioRoutes.js
Labels: 🔨 Refactor

#52 [REFACTOR] 검색 api 파이프라인 사용 및 파이프라인 리팩토링
  controllers/portfolioController.js
  pipeline/portfolioPipeline.js
  routes/portfolioRoutes.js
Labels: 🔨 Refactor

#53 [REFACTOR] 유저 API 리팩토링 진행
  controllers/userController.js
  pipeline/userPipeline.js
  routes/userRoutes.js
Labels: 🔨 Refactor
