Repository dalsu0222/NFE1-1-3-DevPorest_Backend, pull requests merged in 2024-11, with the labels that each got.

#58 [FEAT] 포트폴리오 검색 api 새로 생성 및 파이프라인 api끼리 공통 적용
  controllers/portfolioController.js
  models/Portfolio.js
  pipeline/portfolioPipeline.js
  pipeline/portfolioSearchPipeline.js
  routes/portfolioRoutes.js
Labels: ✨ Feature, 🔨 Refactor

#61 [REFACTOR] portfolio 생성 및 수정 response refactor
  controllers/portfolioController.js
  routes/portfolioRoutes.js
Labels: 🔨 Refactor

#62 [REFACTOR] 기술스택 통계 API 쿼리 파라미터 수정
  controllers/techStackController.js
  routes/techStackRoute.js
Labels: 🔨 Refactor

#65 DevPorest 서버 배포 1.0v
  controllers/authController.js
  controllers/commentController.js
  controllers/jobGroupController.js
  controllers/portfolioController.js
  controllers/techStackController.js
  controllers/userController.js
  index.js
  middleware/auth.js
  middleware/upload.js
  models/Comment.js
  models/JobGroup.js
  models/Like.js
  models/Portfolio.js
  models/TechStack.js
  models/User.js
  package-lock.json
  package.json
  pipeline/portfolioSearchPipeline.js
  pipeline/userPipeline.js
  routes/authRoute.js
  routes/commentRoutes.js
  routes/index.js
  routes/jobGroupRoute.js
  routes/portfolioRoutes.js
  routes/techStackRoute.js
  routes/userRoutes.js
  swagger/index.js
  utils/viewCounter.js
Labels: 🌏 Deploy

#67 [FIX] authController 배포 주소로 변경
  controllers/authController.js
Labels: 🐞 BugFix, 🌏 Deploy

#72 ♻️ 파이프라인 페이지네이션 적용
  pipeline/portfolioSearchPipeline.js
Labels: 🐞 BugFix

#73 [FEAT] jwt 관리 방법 변경 및 내 정보 조회 API 구현
  controllers/authController.js
  controllers/userController.js
  middleware/auth.js
  routes/userRoutes.js
Labels: ✨ Feature, 🔨 Refactor

#75 [FIX} 내 정보 조회 auth middleware 추가
  routes/userRoutes.js
Labels: 🐞 BugFix

#77 🐛 페이지네이션 totalCount 수정
  controllers/portfolioController.js
Labels: 🐞 BugFix, 🔨 Refactor

#78 🐛 검색조건이 반영된 페이지네이션 적용
  controllers/portfolioController.js
  pipeline/portfolioSearchPipeline.js
Labels: 🐞 BugFix

#80 [FEAT] S3 동적 이미지 경로 설정
  middleware/upload.js
  routes/portfolioRoutes.js
  routes/userRoutes.js
Labels: ✨ Feature

#82 ♻️ 썸네일 및 컨텐츠 이미지 처리 url 수정
  middleware/upload.js
Labels: 🔨 Refactor

#86 ♻️ 포트폴리오 조회 시 기술스택 순서 유지
  pipeline/portfolioSearchPipeline.js
Labels: 🔨 Refactor

#88 [FIX] 포트폴리오 수정 시 이미지 인덱스 꼬임 현상 수정
  index.js
  middleware/upload.js
Labels: 🐞 BugFix, ⚙ Setting

#90 [FEAT] 배포 환경 설정
  controllers/authController.js
  swagger/index.js
Labels: 🌏 Deploy, ⚙ Setting

#92 [DEPLOY] cloudtype 배포 에러 수
  controllers/authController.js
  index.js
  middleware/upload.js
  package.json
  pipeline/portfolioSearchPipeline.js
  swagger/index.js
Labels: 🌏 Deploy
